enum TiposToken
{
  PARENT_IZQ,
  PARENT_DER,
  CORCHETE_IZQ,
  CORCHETE_DER,
  LLAVE_IZQ,
  LLAVE_DER,
  Punto,
  DOSPUNTOS,
  COMA,
  PUNTOYCOMA,

  //Palabras reservadas
  Algoritmo,
  Declaracion,
  Constantes,
  Variables,
  Inicio,
  Fin,
  
  Si,
  Sino,
  Fsi,
  Caso,
  FCaso,
  Mientras,
  Fmientras,
  Hacer,
  Para,
  Fpara,
  Hasta,
  Repetir,
  Arreglo,
  De,
  Registro,
  Fregistro,
  Modulo,
  Fmodulo,
  Llamar,
  Devolver,
  Apuntador,
  Reservar,
  Liberar,
  Escribir,
  Leer,
  Archivo,
  AbrirArchivo,
  CerrarArchivo,
  EscribirArchivo,
  LeerArchivo,
  FDA,
  BorrarArchivo,
  RenombrarArchivo,


  Clase,
  Fclase,
  Metodo,
  Fmetodo,
  Nuevo,


  //Operadores
  Mas,
  Menos,
  Por,
  Div,
  Mod,
  Igual,
  DobleIgual,
  Diferente,
  Mayor,
  MayorIgual,
  Menor,
  MenorIgual,
  Y,
  O,
  Negacion,
  Incremento,
  Decremento,
  Asignacion,
  MasIgual,
  MenosIgual,
  MultiplicacionIgual,
  DivisionIgual,
  ModIgual,

  VERDADERO,
  FALSO,

  TipoEntero,
  TipoReal,
  TipoCaracter,
  TipoCadena,
  TipoBooleano,


  NUMERO,
  ENTERO,
  REAL,
  CARACTER,
  CADENA,
  IDENTIFICADOR,
  EOF
}

//Equivalencia de lexemas:
const Map<String,TiposToken> mapaTipos = {
  '(': TiposToken.PARENT_IZQ,
  ')': TiposToken.PARENT_DER,
  '[': TiposToken.CORCHETE_IZQ,
  ']': TiposToken.CORCHETE_DER,
  '{': TiposToken.LLAVE_IZQ,
  '}': TiposToken.LLAVE_DER,
  '.': TiposToken.Punto,
  ':': TiposToken.DOSPUNTOS,
  ',': TiposToken.COMA,
  ';': TiposToken.PUNTOYCOMA,
  'algoritmo': TiposToken.Algoritmo,
  'declaracion': TiposToken.Declaracion,
  'constantes': TiposToken.Constantes,
  'variables': TiposToken.Variables,
  'inicio': TiposToken.Inicio,
  'fin': TiposToken.Fin,
  'si': TiposToken.Si,
  'sino': TiposToken.Sino,
  'fsi': TiposToken.Fsi,
  'caso': TiposToken.Caso,
  'fcaso': TiposToken.FCaso,
  'mientras': TiposToken.Mientras,
  'fmientras': TiposToken.Fmientras,
  'hacer': TiposToken.Hacer,
  'para': TiposToken.Para,
  'fpara': TiposToken.Fpara,
  'hasta': TiposToken.Hasta,
  'repetir': TiposToken.Repetir,
  'arreglo': TiposToken.Arreglo,
  'de': TiposToken.De,
  'registro': TiposToken.Registro,
  'fregistro': TiposToken.Fregistro,
  'modulo': TiposToken.Modulo,
  'fmodulo': TiposToken.Fmodulo,
  'llamar': TiposToken.Llamar,
  'devolver': TiposToken.Devolver,
  'apuntador': TiposToken.Apuntador,
  'reservar': TiposToken.Reservar,
  'liberar': TiposToken.Liberar,
  'escribir': TiposToken.Escribir,
  'leer': TiposToken.Leer,
  'archivo': TiposToken.Archivo,
  'abrirarchivo': TiposToken.AbrirArchivo,
  'cerrararchivo': TiposToken.CerrarArchivo,
  'verdadero':TiposToken.VERDADERO,
  'falso':TiposToken.FALSO,
  
  'entero': TiposToken.TipoEntero,
  'real': TiposToken.TipoReal,
  'caracter':TiposToken.TipoCaracter,
  'cadena':TiposToken.TipoCadena,
  'bool':TiposToken.TipoBooleano,
};

